### ISSUE TITLE
Missing Modules

### ISSUE THREAD

**Issue by starvingtodeathingravy** [chopicalqui/KaliIntelligenceSuite#3]
──(root💀kali)-[/opt/kaliintelsuite/kis]
└─# python3 kismanage.py database --setup-dbg
Traceback (most recent call last):
  File "/opt/kaliintelsuite/kis/kismanage.py", line 36, in <module>
    from database.utils import Engine
  File "/opt/kaliintelsuite/kis/database/utils.py", line 25, in <module>
    import passgen
ModuleNotFoundError: No module named 'passgen'

**Comment by chopicalqui** [comment]
Hey @starvingtodeathingravy 

Thanks for reporting the issue.

Based on your output, I assume that you did the manual installation of KIS and did not use the Docker image. If this is the case, then at some point, you executed the following commands:

```
kali@kali: ~ $ sudo su -
root@kali: ~ # cd /opt/kaliintelsuite
root@kali: /opt/kaliintelsuite # export POETRY_VIRTUALENVS_IN_PROJECT=true
root@kali: /opt/kaliintelsuite # export POETRY_VIRTUALENVS_PATH=/opt/kaliintelsuite/.venv/
root@kali: /opt/kaliintelsuite # poetry install --no-root --no-dev
root@kali: /opt/kaliintelsuite # poetry shell
```

Among other things, these commands create a new Python3 virtual environment for KIS in the directory `/opt/kaliintelsuite/.venv/` and install all necessary packages including `passgen` there.

Your output suggests that you did not activate KIS' Python3 virtual environment before you used `kismanage`. As documented below, I could replicate your output and activating KIS' Python3 virtual environment (using the `source` command) fixed the problem:
```
┌──(root💀kali)-[~]
└─# kismanage -l
Traceback (most recent call last):
  File "/usr/bin/kismanage", line 36, in <module>
    from database.utils import Engine
  File "/opt/kaliintelsuite/kis/database/utils.py", line 25, in <module>
    import passgen
ModuleNotFoundError: No module named 'passgen'

┌──(root💀kali)-[~]
└─# source /opt/kaliintelsuite/.venv/bin/activate

┌──(.venv)─(root💀kali)-[~]
└─# kismanage -l
database does not contain any workspaces

┌──(.venv)─(root💀kali)-[~]
└─# 
```

Note that you have activate the KIS' Python3 virtual environment each time you open a new console or change the user context.

For more information about Python3 virtual environments, refer to:
https://docs.python.org/3/tutorial/venv.html

I will update the documentation to clarify this.

Thanks and cheers

**Comment by chopicalqui** [comment]
Update documentation in wiki page [Installing KIS](https://github.com/chopicalqui/KaliIntelligenceSuite/wiki/Installing-KIS#final-note)
